### ISSUE TITLE
How to get the StringFileInfo block?

### ISSUE THREAD

**Issue by mk-pmb** [ironSource/portable-executable#1]
I managed to read my .exe file and dump it as in the readme example, but I can't find the StringFileInfo data in the output. Do you have any pointers for where to look or how to debug this?

**Comment by AlexeyTolstopyatov** [comment]
### Type of data
We can say that inside the Microsoft executable file (specifically PE), many data structures are embedded/compiled, so you can't just find the string ```StringFileInfo```. And to understand data structures as raw files (literally files) is also not acceptable. 

### Differences...
The location of the resource file, _if I remember myself correctly_ , is very *dependent* on the compiler and other tools that were used to build/line up the binary file.
But in most cases, as I noticed, you can search for this in the`. rdata`section
The simplest thing that can be used to find a resource file is Resource Hacker. 

example:
![image](https://github.com/user-attachments/assets/41813409-578f-4e80-8474-6def9b0881a6)

To find ``` rdata```, you can read about the _PE header_ of the binary file. In its optional part, after all the characteristics, next sections are _the relocation table_.

**Comment by mk-pmb** [comment]
Unfortunately I don't remember what this was about, so I'll close it until I (maybe, some day) rediscover that old project.
